### ISSUE TITLE
Failed to fetch, this bug happens once per day

### ISSUE THREAD

**Issue by rocky3xr** [ETCDEVTeam/emerald-wallet#705] opened 2018-07-08 14:52 UTC
``` 
TypeError: Failed to fetch 
 While processing action: 
 function (dispatch, getState, api) {
    return api.geth.eth.getSyncing().then(function (result) {
      if ((typeof result === 'undefined' ? 'undefined' : _typeof(result)) === 'object') {
        return dispatch({
          type: _actionTypes2.default.SYNCING,
          syncing: true,
          status: result
        });
      }

      dispatch({
        type: _actionTypes2.default.SYNCING,
        syncing: false
      });
    });
  }
 ```

**Comment by BelfordZ** [comment] 2018-07-19 16:32
Dupe of #676 

Thats for submitting it. We are working on having this fixed for the next release.

**Closed by BelfordZ** 2018-07-19 16:32 UTC
