### ISSUE TITLE
Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by sathebm** [ETCDEVTeam/emerald-wallet#747] opened 2018-08-06 23:55 UTC
``` 
JsonRpcError: Insufficient funds for gas * price + value
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/sathe/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23949:30)
    at new JsonRpcError (file:///C:/Users/sathe/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23978:116)
    at file:///C:/Users/sathe/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24015:19
    at <anonymous>
 ```

**Comment by BelfordZ** [comment] 2018-08-09 18:53
duplicate of #750

**Closed** 2018-08-10 14:35 UTC
Labels: Bug
