### ISSUE TITLE
Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by shiehso** [ETCDEVTeam/emerald-wallet#718] opened 2018-07-13 16:15 UTC
``` 
JsonRpcError: Insufficient funds for gas * price + value
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/jumper/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23949:30)
    at new JsonRpcError (file:///C:/Users/jumper/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23978:116)
    at file:///C:/Users/jumper/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24015:19
    at <anonymous>
 ```

**Comment by shanejonas** [comment] 2018-07-17 23:28
hey @shiehso looks like you didn't have enough funds to be able to make that transaction

**Comment by BelfordZ** [comment] 2018-07-19 16:08
Yep. That said, there should be a human readable error dialog should this happen. 

Also, perhaps the form should disable submit if you dont have the min gas amount?

**Comment by BelfordZ** [comment] 2018-07-19 16:21
dupe of #710

**Closed by BelfordZ** 2018-07-19 16:21 UTC
