### ISSUE TITLE
Recent Transactions not Always Showing in History

### ISSUE THREAD

**Issue by chipbit** [ETCDEVTeam/emerald-wallet#575] opened 2018-05-08 22:25 UTC
1) I set up a new wallet, and synced entire chain (up to date)
2) I then sent  a few transactions from another account to the new account created in emerald, at different intervals over the next 12 hours
3) Some of the transactions appear in the log history, some do not.

summary: inconsistent display history of  recent transactions.

OS: Windows Server 2012 R2 DC edition, x64.   
Emerald RC4, R10

**Comment by shanejonas** [comment] 2018-05-18 06:17
duplicate of #473

**Closed** 2018-05-18 06:17 UTC
Labels: Backlog, Doing
